# 基础镜像
FROM golang:1.19-alpine

# 设置工作目录
WORKDIR /app

# 复制资产采集脚本到容器
COPY ./asset_collector /usr/local/bin/asset_collector

# 下载 Neo4j Go 驱动依赖
RUN go mod init asset_collector && \
    go get github.com/neo4j/neo4j-go-driver/v5/neo4j

# 编译资产采集脚本
RUN go build -o /usr/local/bin/asset_collector/asset_collector /usr/local/bin/asset_collector/main.go

# 设置入口命令
CMD ["/usr/local/bin/asset_collector/asset_collector"]
